### ISSUE TITLE
Request adaptation Zygisk Assistant

### ISSUE THREAD

**Issue by Keeperorowner** [PerformanC/ReZygisk#55]
### Version

v1.0.0 (234-f1ba34f-release)

### Modules

Zygisk Assistant

### Description

After the Zygisk Assistant is installed and restarted, another restart is forced, after which the Zygisk Assistant module disappears

### Steps to reproduce

normal operation

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
There is nothing wrong with ReZygisk itself, numerous people have been using Zygisk Assistant with it flawlessly. It's likely to be something else. If anything, please provide boot logs (specifically the logcat) here

**Comment by ThePedroo** [comment]
Besides, that too. I do not recommend the use of Zygisk Assistant when using main branch -- Not only it doesn't help with any app, but also brings incompatibility with other modules.

In any case, Zygisk Assistant, when I used to use, did work, and main branch didn't change since then. If you need help, please hop on our Discord or Telegram and post logcat so that we can try to help
