### ISSUE TITLE
[FR]: Hide loaded module from linker solist and somain list

### ISSUE THREAD

**Issue by ThePedroo** [PerformanC/ReZygisk#9]
### Description

The merge of Reveny's PR (https://github.com/Dr-TSNG/ZygiskNext/pull/79) into ReZygisk.

### Reason

Modules like Shamiko are currently not working, and requires a signed build from Zygisk Next (if any Shamiko dev sees this, feel free to correct me), leaving users with no option if not Shamiko 0.7.5 or FOSS Zygisk Assistant.

However, we can't expect them to use those modules to hide and do nothing in our side, we should try to make the injections as hidden as possible.

### Confirmations

- [X] This feature is not already implemented.
- [X] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CoelacanthusHex** [comment]
There is a regression: if you flash some module to update the GPU driver (e.g. GPU_v782_M-KSU.zip from https://t.me/lhmodshare) and set HWUI renderer to skiavk via `debug.hwui.renderer=skiavk` system.prop, you will get metadata mismatched and a black screen in applications with unloaded modules. This problem was introduced in https://github.com/PerformanC/ReZygisk/commit/af96b85a91ba3d1107884c61484f276cc1a4caff and the issue disappeared after switching back to https://github.com/PerformanC/ReZygisk/commit/4aa8b2f8282e7d67fdedefd80250a8fa390f4b38. So it should be a regression of https://github.com/PerformanC/ReZygisk/commit/af96b85a91ba3d1107884c61484f276cc1a4caff.
log is like this:
```
09-05 14:33:47.243  7536  8145 E AdrenoUtils: <validate_resource_memory_layout_metadata:2073>: Metadata driver version mismatch {store uuid 04000000-0100-0000-0100-000000000000, struct uuid 02000000-0000-0000-0000-000000000000}
09-05 14:33:47.243  7536  8145 E HWUI    : SkSurfaces::WrapAndroidHardwareBuffer failed
09-05 14:33:47.243  7536  8145 E HWUI    : VulkanSurface::dequeueNativeBuffer called with an invalid surface!
```
